# trialID Format: ddmmyy.{trial number}
# trial_descript Format: {experiment dataset}_{trial description}
trialID:        "030226.3"
trial_descript: "SpikeExp3_SanityCheck"
exp_name:       "exp3_lungcancer_plasmatrial_110524"
raw_dir:        "Exp_Data/exp3_lungcancer_plasmatrial_110524/OUTPUT/Data/fastq"


ip_root:        "IP_Data/"
out_root:       "Exp_Output/"
script_dir:     "scripts"

#--------------------------
# REFERENCE GENOMES
#--------------------------
host_ref: "Ref_Data/Mus_musculus.GRCm38.cdna.all.fa"
viral_ref: "Ref_Data/all.viral.fna"
bact16s_ref: "Ref_Data/all.rrna.bacteria"

#--------------------------
# UMI SELECTION PARAMETERS
#--------------------------
r1_primer: "CCTACGGGNGGCWGCAG"
r2_primer: "GGACTACHVGGGTATCTAATCC"

# r2 Motif length chosen based on default in previous pipeline
#     Note: motif up to first semi-ambiguous nucleotide in primer
#     Did the same thing in selecting r1 primer motif length
r1_primer_motif_len: 8
r2_primer_motif_len: 7
umi_len: 9
max_offset: 5
r2_primer_skip: false
poly_G_threshold: 1.0


#------------------------
# TRIMMOMATIC PARAMETERS
#------------------------
trimmomatic_jar: "$TRIMMOJAR"
trim_args: ["AVGQUAL:30"]

#--------------------
# DADA2 PARAMETERS
#--------------------
# Chunked processing Params
chunk_size: 5

# filterandTrim Params
truncLen: 190
maxN: 0
maxEE: 2
truncQ: 2


#------------------------
# MOTHUR PARAMETERS
#------------------------
mothur_reference: "Ref_Data/ncbi20.fasta"
mothur_tax_file: "Ref_Data/ncbi20.tax"
mothur_cutoff: 0
mothur_method: "wang"


#------------------------
# KRAKEN PARAMETERS
#------------------------
#current options: [silva, greengenes, ncbi20_k2]
kraken_db: "greengenes"

#---------------------------
# TAXONOMY COUNT PARAMETERS
#---------------------------
tax_min_counts:
  phylum: 50
  class: 50
  genus: 10
  species: 5

#-------------------------------------
# READ COUNT NORMALIZATION PARAMETERS
#-------------------------------------
#current options: [noNorm, rawTSS, hostTSS, log2, rawTSSlog2, hostTSSlog2]
norm_method: "log2"
norm_offset: 1

#-----------------------------
# PYLOSEQ PARAMETERS
#-----------------------------
add_unclassified_prefix: false


#-----------------------------
# NEGATIVE CONTROL PARAMETERS
#-----------------------------
neg_tags: ["NEGATIVECONTROL", "CELLSCONTROL", "NEGWATER", "BLANK", "NEGcDNA", "NEGPCR", "NEG"]
neg_db_top_k: 10000
neg_as_keep_lt: 160