{
  "add_unclassified_prefix": true,
  "bact16s_ref": "Ref_Data/all.rrna.bacteria",
  "batch_label": "SpikeInExp1",
  "batch_table": "experiment_batch_configs.tsv",
  "chunk_size": 5,
  "conf_cutoff": 0.2,
  "exp_dir": "SpikeIns/SpikeInExp1_Data",
  "host": "human",
  "human_ref": "Ref_Data/clean.human.fa",
  "in_root": "Exp_Data/",
  "include_analysis": "false",
  "include_processing": "true",
  "ip_root": "IP_Data/",
  "kraken_db": "ncbi20_k2",
  "maxEE": 2,
  "maxN": 0,
  "max_offset": 5,
  "metadata": "SpikeIns/SpikeInExp1_Data/SpikeInExp1_metadata.xlsx",
  "mothur_cutoff": 0,
  "mothur_method": "wang",
  "mothur_reference": "Ref_Data/ncbi20.fasta",
  "mothur_tax_file": "Ref_Data/ncbi20.tax",
  "mouse_ref": "Ref_Data/Mus_musculus.GRCm38.cdna.all.fa",
  "out_root": "Exp_Output/",
  "poly_G_threshold": 1.0,
  "r1_primer": "CCTACGGGNGGCWGCAG",
  "r1_primer_motif_len": 8,
  "r2_primer": "GGACTACHVGGGTATCTAATCC",
  "r2_primer_motif_len": 7,
  "r2_primer_skip": false,
  "script_dir": "scripts",
  "tax_min_counts": {
    "class": 50,
    "genus": 10,
    "phylum": 50,
    "species": 5
  },
  "trialID": "070926.1",
  "trial_descript": "SpikeInExp1_Rerun",
  "trim_args": [
    "AVGQUAL:30"
  ],
  "trimmomatic_jar": "$TRIMMOJAR",
  "truncLen": 190,
  "truncQ": 2,
  "umi_len": 9,
  "viral_ref": "Ref_Data/all.viral.fna"
}
